Created Footer
YoshithaRathnayake/DineEase-Application pull request #6
Opened 2023-08-28 04:33 UTC by tharuka01

## Purpose

The purpose of this PR is to fix #3

## Approach

### Screenshots

  
### Preview Link

https://pr-{PR_NUMBER}-dine-ease.surge.sh/

2023-08-29 17:29 UTC, YoshithaRathnayake requested changes

2023-08-29 17:29 UTC, YoshithaRathnayake commented on index.html
> +      © 2020 Copyright:
```suggestion
      © 2023 DineEase | Browse Restaurants
```

2023-08-29 17:32 UTC, YoshithaRathnayake requested changes

2023-08-29 17:32 UTC, YoshithaRathnayake commented on index.html
> +      © 2020 Copyright:
```suggestion
      © 2023
```

2023-08-29 17:32 UTC, YoshithaRathnayake commented on index.html
> +         >DineEase.org</a
```suggestion
         > DineEase | Browse Restaurants</a
```

2023-08-29 17:33 UTC, YoshithaRathnayake requested changes
![image](https://github.com/YoshithaRathnayake/DineEase-Application/assets/97069900/9a531425-13bf-40a8-86a0-2861ec48d44c)
 
Remove the underline of these links @tharuka01

2023-08-29 17:34 UTC, YoshithaRathnayake requested changes
![image](https://github.com/YoshithaRathnayake/DineEase-Application/assets/97069900/282702d9-5f31-4aeb-bc34-a9206bd120c8)

Can you see the underscore after every icon without github one?
Try to remove that pls

2023-08-30 05:59 UTC, tharuka01 commented
> ![image](https://user-images.githubusercontent.com/97069900/264104149-9a531425-13bf-40a8-86a0-2861ec48d44c.png)
> 
> Remove the underline of these links @tharuka01

Fixed

2023-08-30 15:10 UTC, YoshithaRathnayake requested changes

2023-08-30 15:10 UTC, YoshithaRathnayake commented on assets/css/styles.css
> +a {
Just remove this bcs I also add the same

```suggestion
```

2023-08-30 15:10 UTC, YoshithaRathnayake commented on assets/css/styles.css
> +    text-decoration: none;
```suggestion
```

2023-08-30 15:10 UTC, YoshithaRathnayake commented on assets/css/styles.css
> +}
```suggestion
```

2023-09-05 16:47 UTC, closed without merging